#version 450
layout(local_size_x = 128) in;
layout(std430, binding = 0) readonly buffer A { float dY[]; };
layout(std430, binding = 1) readonly buffer B { float mask[]; };
layout(std430, binding = 2) buffer C { float dX[]; };
layout(push_constant) uniform P { int total; } pc;
void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= uint(pc.total)) return;
    int src_idx = floatBitsToInt(mask[i]);
    dX[src_idx] += dY[i];
}
