#version 450
layout(local_size_x = 24, local_size_y = 1, local_size_z = 1) in;
layout(std430, binding = 0) readonly buffer Input { float input_data[]; };
layout(std430, binding = 1) readonly buffer Unused { float unused_data[]; };
layout(std430, binding = 2) writeonly buffer Output { float output_data[]; };

void main() {
    uint i = gl_LocalInvocationID.x;
    if (i >= 24) { return; }
    output_data[i] = max(input_data[i], 0.0);
}
