#version 450
layout(local_size_x = 10, local_size_y = 1, local_size_z = 1) in;
layout(std430, binding = 0) readonly buffer Input { float input_data[]; };
layout(std430, binding = 1) readonly buffer Unused { float unused_data[]; };
layout(std430, binding = 2) writeonly buffer Output { float output_data[]; };

void main() {
    uint i = gl_LocalInvocationID.x;
    if (i >= 10) { return; }
    float m = input_data[0];
    for (uint j = 1; j < 10; ++j) {
        m = max(m, input_data[j]);
    }
    float sum = 0.0;
    for (uint j = 0; j < 10; ++j) {
        sum += exp(input_data[j] - m);
    }
    output_data[i] = exp(input_data[i] - m) / sum;
}
